# Uncomment the next line to define a global platform for your project
platform :ios, '13.6'

target 'smack-chat-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  use_frameworks!

  # Pods for smack-chat-app
  
  pod 'Alamofire'
  pod 'Socket.IO-Client-Swift'

end
